version: '2.1'

services:
  nexus3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: doggie6/nexus3:3.4.0
    command: ["bin/nexus", "run"]
    entrypoint: ["/opt/sonatype/nexus/entrypoint.sh"]
    container_name: nexus3
    hostname: nexus3
    volumes:
      - /tmp/nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "5000:5000"
      - "5001:5001"
    environment:
      JAVA_MAX_HEAP: 1200m
      JAVA_MIN_HEAP: 1200m
      # EXTRA_JAVA_OPTS: